- name: ensure keystone user
  run_once: true
  delegate_to: "{{ groups[openstack_group_controller][0] }}"
  keystone_v3_user:
    name: "{{ user }}"
    password: "{{ password }}"
    force: "{{ keystone_force_change_password }}"
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"

- name: ensure keystone user has admin role on project
  run_once: true
  delegate_to: "{{ groups[openstack_group_controller][0] }}"
  keystone_v3_assignment:
    user: "{{ user }}"
    project: "{{ project }}"
    role: admin

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
