- name: ensure keystone image service
  keystone_v3_service:
    name: glance
    type: image
    state: present
      
    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"

- name: ensure keystone image endpoints
  keystone_v3_endpoint:
    service: glance
    region: "{{ openstack_region }}"
    interface: "{{ item.key }}"
    url: "{{ item.value }}"
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
  with_dict:
    public: "{{ keystone_endpoint_image_public }}"
    internal: "{{ keystone_endpoint_image_internal }}"
    admin: "{{ keystone_endpoint_image_admin }}"

- name: ensure keystone service user
  keystone_v3_user:
    name: "{{ glance_keystone_user }}"
    password: "{{ glance_keystone_password }}"
    state: present
      
    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"

- name: ensure keystone service user has admin role on service project
  keystone_v3_assignment:
    user: "{{ glance_keystone_user }}"
    project: "{{ glance_keystone_project }}"
    role: admin
   
    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
