- name: ensure ceph images pool
  ceph_pool:
    name: images
    state: present

- name: retrieve ceph client keyring
  command: >
    ceph auth get-or-create client.glance
        mon 'allow r'
        osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'
      -o /etc/ceph/ceph.client.glance.keyring
  args:
    creates: /etc/ceph/ceph.client.glance.keyring
