- include: configure_keystone.yml
  when: swift_configure_keystone
  tags:
    - swift

- name: install swift
  apt:
    pkg: swift
    state: present
  tags:
    - swift
    - swift-install

- name: install python swift client
  apt:
    pkg: python-swiftclient
    state: present
  tags:
    - swift
    - swift-install

- name: ensure config directory
  file:
    path: /etc/swift
    state: directory
  tags:
    - swift
    - swift-install

- include: role_controller.yml
  when: swift_role_controller
  tags:
    - swift

- include: role_storage.yml
  when: swift_role_storage
  tags:
    - swift

- name: configure swift
  template:
    src: swift.conf.j2
    dest: /etc/swift/swift.conf
  notify:
    - restart swift services
  tags:
    - swift
    - swift-configure

- include: build_rings.yml
  tags:
    - swift
    - swift-configure
    - swift-rings-build

- meta: flush_handlers
