- name: install swift-proxy
  apt:
    pkg: swift-proxy
    state: present

- name: configure swift-proxy
  template:
    src: proxy-server.conf.j2
    dest: /etc/swift/proxy-server.conf
  notify:
    - restart swift services

- name: configure dispersion
  template:
    src: dispersion.conf.j2
    dest: /etc/swift/dispersion.conf
