- name: sync glance db
  run_once: true
  command: glance-manage db_sync

- name: restart glance-api
  service:
    name: glance-api
    state: restarted
  failed_when: false

- name: restart glance-registry
  service:
    name: glance-registry
    state: restarted
  failed_when: false
