- name: sync glance db
  command: glance-manage db_sync

- name: restart glance-api
  service:
    name: glance-api
    state: restarted

- name: restart glance-registry
  service:
    name: glance-registry
    state: restarted
