# MySQL configuration
keystone_mysql_user: keystone
keystone_mysql_password: keystone
keystone_mysql_db: keystone
keystone_mysql_host: "{{ openstack_mysql_host }}"

# Memcached configuration
keystone_memcache_servers: "{{ openstack_memcache_hosts }}"

# Keystone configuration
keystone_identity_endpoints:
  public: "http://{{ openstack_controller_public_host }}:5000/v2.0"
  internal: "http://{{ openstack_controller_internal_host }}:5000/v2.0"
  admin: "http://{{ openstack_controller_internal_host }}:35357/v2.0"

keystone_token_provider: fernet

keystone_listen_address: 0.0.0.0

keystone_rotate_fernet_keys: false
