dependencies:
  - role: openstack-common
  - role: ubuntu-cloud-archive

  - role: openstack/keystone-service
    service_name: designate
    service_type: dns
    service_endpoints: "{{ designate_keystone_dns_endpoints }}"
    tags:
      - designate

  - role: openstack/keystone-service-user
    user: "{{ designate_keystone_user }}"
    password: "{{ designate_keystone_password }}"
    project: "{{ designate_keystone_project }}"
    tags:
      - designate

  - role: openstack/database
    database: "{{ designate_mysql_db }}"
    user: "{{ designate_mysql_user }}"
    password: "{{ designate_mysql_password }}"
    tags:
      - designate

  - role: openstack/messaging
    vhost: "{{ designate_rabbitmq_vhost }}"
    user: "{{ designate_rabbitmq_user }}"
    password: "{{ designate_rabbitmq_password }}"
    tags:
      - designate
