dependencies:
  - role: openstack-common
  - role: ubuntu-cloud-archive

  - role: openstack/keystone-service
    service_name: designate
    service_type: dns
    service_endpoints: "{{ designate_keystone_dns_endpoints }}"
    when: designate_configure_keystone
    tags:
      - designate

  - role: openstack/keystone-service-user
    user: "{{ designate_keystone_user }}"
    password: "{{ designate_keystone_password }}"
    project: "{{ designate_keystone_project }}"
    when: designate_configure_keystone
    tags:
      - designate

  - role: openstack/database
    database_name: "{{ designate_mysql_db }}"
    database_user: "{{ designate_mysql_user }}"
    database_password: "{{ designate_mysql_password }}"
    database_login_host: "{{ designate_mysql_host }}"
    database_login_user: root
    database_login_password: "{{ designate_mysql_login_password }}"
    when: designate_configure_mysql
    tags:
      - designate
