# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "10.0.44.10"
  config.vm.network "private_network", ip: "10.0.55.10", auto_config: false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 6144
    vb.cpus = 2

    # Workaround for slow DNS resolution on OS X host
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

    # Enable promiscuous mode
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
  end

  config.vm.provision "ansible" do |a|
    a.sudo = true
    a.playbook = "playbook.yml"
  end
end
