openstack_region: RegionOne

openstack_configure_haproxy: false

openstack_internal_interface: eth0
openstack_internal_host: "{{ ansible_default_ipv4.address }}"

openstack_controller_internal_host: localhost
openstack_controller_public_host: localhost

openstack_memcache_hosts:
  - "{{ openstack_controller_internal_host }}:11211"

openstack_mysql_host: "{{ openstack_controller_internal_host }}"

openstack_rabbitmq_hosts:
  - "{{ openstack_controller_internal_host }}:5672"

openstack_rabbitmq_vhost: openstack

keystone_admin_token: ADMIN
keystone_admin_endpoint: "http://{{ openstack_controller_internal_host }}:35357/v3"
keystone_auth_url: "http://{{ openstack_controller_internal_host }}:5000/v2.0"

keystone_admin_email: admin@example.com
keystone_admin_password: password

openstack_metadata_proxy_shared_secret: secret

openstack_group_compute: compute
openstack_group_controller: controller
openstack_group_mysql: mysql
openstack_group_rabbitmq: rabbitmq

keystone_force_change_password: false
