dependencies:
  - role: openstack-common
  - role: apache2
  - role: ceph-client

  - role: openstack/lb
    name: radosgw
    listen_port: 8080
    options:
      - httpchk HEAD /
    tags:
      - radosgw

  - role: openstack/keystone-service
    service_name: swift
    service_type: object-store
    service_endpoints: "{{ radosgw_keystone_objectstore_endpoints }}"
    tags:
      - radosgw
