- name: install nova-compute
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: nova_compute_packages[nova_compute_libvirt_virt_type]
  tags:
    - nova
    - nova-install

- include: libvirt.yml
  tags:
    - nova
    - nova-configure

- include: libvirt_rbd_secret.yml
  when: nova_configure_ceph
  tags:
    - nova
    - nova-configure

- name: configure nova-compute
  template:
    src: nova-compute.conf.j2
    dest: /etc/nova/nova-compute.conf
  notify:
    - restart nova-compute
  tags:
    - nova
    - nova-configure

- include: ssh.yml
  when: nova_distribute_ssh_keys
  tags:
    - nova
    - nova-configure
    - nova-distribute-ssh

- include: configure_ceph.yml
  when: nova_configure_ceph
  tags:
    - nova
    - nova-configure

- meta: flush_handlers
