- name: copy authorized keys
  copy:
    src: fetch/nova-authorized-keys
    dest: /var/lib/nova/.ssh/authorized_keys
    owner: nova
    group: nova
    mode: 0600

- name: copy known hosts file
  copy:
    src: fetch/nova-known-hosts
    dest: /var/lib/nova/.ssh/known_hosts
    owner: nova
    group: nova
    mode: 0644
