- name: ensure fetch directory
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no
  file:
    path: fetch/nova-keys
    state: directory

- name: ensure nova user has ssh key pair
  user:
    name: nova
    generate_ssh_key: yes
    ssh_key_type: ecdsa
    ssh_key_bits: 256
  register: nova_user

- name: fetch nova ssh public key
  fetch:
    src: /var/lib/nova/.ssh/id_ecdsa.pub
    dest: fetch/nova-keys/{{ ansible_hostname }}.pub
    flat: yes

- name: assemble ssh public keys
  delegate_to: 127.0.0.1
  run_once: true
  sudo: no
  assemble:
    src: fetch/nova-keys
    regexp: \.pub$
    dest: fetch/nova-authorized-keys

- name: copy authorized keys
  copy:
    src: fetch/nova-authorized-keys
    dest: /var/lib/nova/.ssh/authorized_keys
    owner: nova
    group: nova
    mode: 0600

- name: add host key to known hosts file
  delegate_to: 127.0.0.1
  sudo: no
  lineinfile:
    dest: fetch/nova-known-hosts
    regexp: ^{{ openstack_internal_host }} .*$
    line: "{{ openstack_internal_host }} ssh-rsa {{ ansible_ssh_host_key_rsa_public }}"
    create: yes

- name: copy known hosts file
  copy:
    src: fetch/nova-known-hosts
    dest: /var/lib/nova/.ssh/known_hosts
    owner: nova
    group: nova
    mode: 0644
