- name: ensure mongodb user
  shell: >
    cat <<EOF | mongo {{ ceilometer_mongodb_host }}/{{ ceilometer_mongodb_db }}
      db.createUser({
        "user": "{{ ceilometer_mongodb_user }}",
        "pwd": "{{ ceilometer_mongodb_password }}",
        "roles": [
          "readWrite",
          "dbAdmin"
        ]
      })
    EOF
