- name: install libvirt
  apt:
    pkg: libvirt-bin
    state: present
  tags:
    - libvirt
    - libvirt-install

- name: configure libvirtd
  template:
    src: libvirtd.conf.j2
    dest: /etc/libvirt/libvirtd.conf
  notify:
    - restart libvirtd
  tags:
    - libvirt
    - libvirt-configure

- name: configure libvirtd defaults
  copy:
    src: libvirt-bin
    dest: /etc/default/libvirt-bin
  notify:
    - restart libvirtd
  tags:
    - libvirt
    - libvirt-configure

- meta: flush_handlers
