- name: install heat
  apt: pkg={{ item }} state=present
  items:
    - heat-api
    - heat-api-cfn
    - heat-engine
  tags:
    - heat
    - heat-install

- name: configure heat
  template:
    src: heat.conf.j2
    dest: /etc/heat/heat.conf
  notify:
    - sync heat db
    - restart heat-api
    - restart heat-api-cfn
    - restart heat-engine
  tags:
    - heat
    - heat-configure

- meta: flush_handlers

- name: ensure sqlite db absent
  file:
    path: /var/lib/heat/heat.sqlite
    state: absent
  tags:
    - heat
