- name: install heat-api
  apt:
    pkg: heat-api
    state: present
  tags:
    - heat
    - heat-install

- name: install heat-api-cfn
  apt:
    pkg: heat-api-cfn
    state: present
  tags:
    - heat
    - heat-install

- name: install heat-engine
  apt:
    pkg: heat-engine
    state: present
  tags:
    - heat
    - heat-install

- name: configure heat
  template:
    src: heat.conf.j2
    dest: /etc/heat/heat.conf
  notify:
    - sync heat db
    - restart heat-api
    - restart heat-api-cfn
    - restart heat-engine
  tags:
    - heat
    - heat-configure

- meta: flush_handlers
