- name: install neutron-metadata-agent
  apt:
    pkg: neutron-metadata-agent
    state: present

- name: configure neutron-metadata-agent
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
  notify:
    - restart neutron-metadata-agent
