- name: ensure keystone network service
  keystone_v3_service:
    name: neutron
    type: network
    state: present
      
    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"

- name: ensure keystone network endpoints
  keystone_v3_endpoint:
    service: neutron
    region: "{{ openstack_region }}"
    interface: "{{ item.key }}"
    url: "{{ item.value }}"
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
  with_dict:
    public: "{{ keystone_endpoint_network_public }}"
    internal: "{{ keystone_endpoint_network_internal }}"
    admin: "{{ keystone_endpoint_network_admin }}"

- name: ensure keystone service user
  keystone_v3_user:
    name: "{{ neutron_keystone_user }}"
    password: "{{ neutron_keystone_password }}"
    state: present
      
    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"

- name: ensure keystone service user has admin role on service project
  keystone_v3_assignment:
    user: "{{ neutron_keystone_user }}"
    project: "{{ neutron_keystone_project }}"
    role: admin
   
    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
