- include: configure_rabbitmq.yml
  when: neutron_configure_rabbitmq
  tags:
    - neutron

- include: configure_sysctl.yml
  tags:
    - neutron

- name: install neutron-common
  apt:
    pkg: neutron-common
    state: present
  tags:
    - neutron
    - neutron-install

- name: install neutron-plugin-ml2
  apt:
    pkg: neutron-plugin-ml2
    state: present
  tags:
    - neutron
    - neutron-install

- include: component_server.yml
  when: neutron_component_server
  tags:
    - neutron

- include: component_dhcp_agent.yml
  when: neutron_component_dhcp_agent
  tags:
    - neutron

- include: component_l3_agent.yml
  when: neutron_component_l3_agent
  tags:
    - neutron

- include: component_lbaas_agent.yml
  when: neutron_component_lbaas_agent
  tags:
    - neutron

- include: component_metadata_agent.yml
  when: neutron_component_metadata_agent
  tags:
    - neutron

- include: component_ovs_agent.yml
  when: neutron_component_ovs_agent
  tags:
    - neutron

- name: configure neutron
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
  notify:
    - sync neutron db
    - restart neutron-server
    - restart neutron-dhcp-agent
    - restart neutron-l3-agent
    - restart neutron-lbaas-agent
    - restart neutron-metadata-agent
    - restart neutron-plugin-openvswitch-agent
  tags:
    - neutron
    - neutron-configure

- name: configure ml2 plugin
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  notify:
    - sync neutron db
    - restart neutron-server
    - restart neutron-dhcp-agent
    - restart neutron-l3-agent
    - restart neutron-lbaas-agent
    - restart neutron-metadata-agent
    - restart neutron-plugin-openvswitch-agent
  tags:
    - neutron
    - neutron-configure

- meta: flush_handlers
