- name: install cinder-api
  apt:
    pkg: cinder-api
    state: present
  tags:
    - cinder
    - cinder-install

- name: install cinder-scheduler
  apt:
    pkg: cinder-scheduler
    state: present
  tags:
    - cinder
    - cinder-install

- meta: flush_handlers
