- name: add apt key
  apt_key:
    id: CD2EFD2A
    url: https://www.percona.com/downloads/RPM-GPG-KEY-percona

- name: add apt repository
  apt_repository:
    repo: "deb http://repo.percona.com/apt trusty main"
    update_cache: yes

- name: install mysql
  apt:
    pkg: percona-xtradb-cluster-56
    state: present

- name: install python mysql client
  apt:
    pkg: python-mysqldb
    state: present
