- name: allow nonlocal bind
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    sysctl_set: yes
  tags:
    - keepalived
    - keepalived-install

- name: install keepalived
  apt:
    pkg: keepalived
    state: present
  tags:
    - keepalived
    - keepalived-install

- name: configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify:
    - restart keepalived
  tags:
    - keepalived
    - keepalived-configure

- meta: flush_handlers
