- name: install neutron-dhcp-agent
  apt:
    pkg: neutron-dhcp-agent
    state: present
  tags:
    - neutron
    - neutron-install

- name: configure neutron-dhcp-agent
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
  notify:
    - restart neutron-dhcp-agent
  tags:
    - neutron
    - neutron-configure

- meta: flush_handlers
