dependencies:
  - role: openstack-common
  - role: ubuntu-cloud-archive

  - role: openstack/keystone-service
    service_name: neutron
    service_type: network
    service_endpoints: "{{ neutron_keystone_network_endpoints }}"
    when: neutron_configure_keystone
    tags:
      - neutron

  - role: openstack/keystone-service-user
    user: "{{ neutron_keystone_user }}"
    password: "{{ neutron_keystone_password }}"
    project: "{{ neutron_keystone_project }}"
    when: neutron_configure_keystone
    tags:
      - neutron

  - role: openstack/database
    database_name: "{{ neutron_mysql_db }}"
    database_user: "{{ neutron_mysql_user }}"
    database_password: "{{ neutron_mysql_password }}"
    database_login_host: "{{ neutron_mysql_host }}"
    database_login_user: root
    database_login_password: "{{ neutron_mysql_login_password }}"
    when: neutron_configure_mysql
    tags:
      - neutron
