dependencies:
  - role: openstack-common
  - role: ubuntu-cloud-archive

  - role: openstack/keystone-service
    service_name: neutron
    service_type: network
    service_endpoints: "{{ neutron_keystone_network_endpoints }}"
    when: neutron_configure_keystone
    tags:
      - neutron

  - role: openstack/keystone-service-user
    user: "{{ neutron_keystone_user }}"
    password: "{{ neutron_keystone_password }}"
    project: "{{ neutron_keystone_project }}"
    when: neutron_configure_keystone
    tags:
      - neutron
