- name: assemble haproxy config
  assemble:
    src: /etc/haproxy/cfg.d
    dest: /etc/haproxy/haproxy.cfg
    regexp: \.cfg$
  notify:
    - reload haproxy

- name: reload haproxy
  service:
    name: haproxy
    state: reloaded
