glance_configure_ceph: false

# MySQL configuration
glance_mysql_user: glance
glance_mysql_password: glance
glance_mysql_db: glance
glance_mysql_host: "{{ openstack_mysql_host }}"

# Keystone configuration
glance_keystone_image_endpoints:
  public: "http://{{ openstack_controller_public_host }}:9292"
  internal: "http://{{ openstack_controller_internal_host }}:9292"
  admin: "http://{{ openstack_controller_internal_host }}:9292"

glance_keystone_user: glance
glance_keystone_password: glance
glance_keystone_project: service
glance_keystone_auth_uri: "http://{{ openstack_controller_public_host }}:5000"
glance_keystone_identity_uri: "http://{{ openstack_controller_internal_host }}:35357"

# Glance configuration
glance_api_workers: 2
glance_registry_workers: 2

glance_default_store: file

glance_stores:
  - file
  - http

glance_swift_auth_url: "http://{{ openstack_controller_internal_host }}:5000/v2.0"
glance_swift_user: "{{ glance_keystone_project }}:{{ glance_keystone_user }}"
glance_swift_key: "{{ glance_keystone_password }}"
glance_swift_region: "{{ openstack_region }}"

glance_listen_address: 0.0.0.0
