- name: ensure demo user
  run_once: true
  keystone_v3_user:
    name: demo
    password: demo
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
  tags:
    - openstack-demo

- name: ensure demo project
  run_once: true
  keystone_v3_project:
    name: demo
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
  tags:
    - openstack-demo

- name: ensure demo user has user role on demo project
  run_once: true
  keystone_v3_assignment:
    user: demo
    project: demo
    role: user
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
  tags:
    - openstack-demo

- name: create external network
  run_once: true
  quantum_network:
    name: ext-net
    router_external: true
    provider_network_type: flat
    provider_physical_network: external
    tenant_name: service
    state: present

    login_username: admin
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: admin
    auth_url: "{{ keystone_auth_url }}"
  tags:
    - openstack-demo

- name: create external subnet
  run_once: true
  quantum_subnet:
    name: ext-subnet
    network_name: ext-net
    cidr: 10.0.55.0/24
    gateway_ip: 10.0.55.1
    allocation_pool_start: 10.0.55.100
    allocation_pool_end: 10.0.55.250
    enable_dhcp: false
    tenant_name: service
    state: present

    login_username: admin
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: admin
    auth_url: "{{ keystone_auth_url }}"
  tags:
    - openstack-demo

- name: create demo network
  run_once: true
  quantum_network:
    name: demo-net
    tenant_name: demo
    state: present

    login_username: admin
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: admin
    auth_url: "{{ keystone_auth_url }}"
  tags:
    - openstack-demo

- name: create demo subnet
  run_once: true
  quantum_subnet:
    name: demo-subnet
    network_name: demo-net
    cidr: 192.168.111.0/24
    dns_nameservers: 8.8.8.8,8.8.4.4
    tenant_name: demo
    state: present

    login_username: admin
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: admin
    auth_url: "{{ keystone_auth_url }}"
  tags:
    - openstack-demo

- name: create demo router
  run_once: true
  quantum_router:
    name: demo-router
    tenant_name: demo
    state: present

    login_username: admin
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: admin
    auth_url: "{{ keystone_auth_url }}"
  tags:
    - openstack-demo

- name: attach demo router to demo subnet
  run_once: true
  quantum_router_interface:
    router_name: demo-router
    subnet_name: demo-subnet
    tenant_name: demo
    state: present

    login_username: admin
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: admin
    auth_url: "{{ keystone_auth_url }}"
  tags:
    - openstack-demo

- name: set demo router gateway
  run_once: true
  quantum_router_gateway:
    router_name: demo-router
    network_name: ext-net
    state: present

    login_username: admin
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: admin
    auth_url: "{{ keystone_auth_url }}"
  tags:
    - openstack-demo

- name: configure demo environment script
  template:
    src: openrc-demo.j2
    dest: /root/openrc-demo
    mode: 0700
    owner: root
    group: root
