- name: ensure mysql db
  mysql_db:
    name: "{{ database }}"
    state: present

    login_host: "{{ login_host }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"

- name: ensure mysql user
  mysql_user:
    name: "{{ user }}"
    host: "%"
    password: "{{ password }}"
    priv: "{{ database }}.*:ALL"
    state: present

    login_host: "{{ login_host }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
