- name: install designate-api
  apt:
    pkg: designate-api
    state: present
  tags:
    - designate
    - designate-install

- name: install designate-central
  apt:
    pkg: designate-central
    state: present
  tags:
    - designate
    - designate-install

- name: copy designate-mdns upstart script
  copy:
    src: designate-mdns.conf
    dest: /etc/init/designate-mdns.conf
  tags:
    - designate
    - designate-install

- name: copy designate-pool-manager upstart script
  copy:
    src: designate-pool-manager.conf
    dest: /etc/init/designate-pool-manager.conf
  tags:
    - designate
    - designate-install

- name: install python designate client
  apt:
    pkg: python-designateclient
    state: present
  tags:
    - designate
    - designate-install

- name: configure designate
  template:
    src: designate.conf.j2
    dest: /etc/designate/designate.conf
  notify:
    - sync designate db
    - restart designate-api
    - restart designate-central
    - restart designate-mdns
    - restart designate-pool-manager
  tags:
    - designate
    - designate-configure

- meta: flush_handlers
