- name: sync neutron db
  command: >
    neutron-db-manage --config-file /etc/neutron/neutron.conf 
      --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  when: neutron_component_server

- name: restart neutron-server
  service:
    name: neutron-server
    state: restarted
  when: neutron_component_server

- name: restart neutron-dhcp-agent
  service:
    name: neutron-dhcp-agent
    state: restarted
  when: neutron_component_dhcp_agent

- name: restart neutron-l3-agent
  service:
    name: neutron-l3-agent
    state: restarted
  when: neutron_component_l3_agent

- name: restart neutron-metadata-agent
  service:
    name: neutron-metadata-agent
    state: restarted
  when: neutron_component_metadata_agent

- name: restart neutron-plugin-openvswitch-agent
  service:
    name: neutron-plugin-openvswitch-agent
    state: restarted
  when: neutron_component_ovs_agent
