cinder_configure_keystone: "{{ openstack_role_controller }}"
cinder_configure_mysql: "{{ openstack_role_controller }}"
cinder_configure_rabbitmq: "{{ openstack_role_controller }}"

cinder_component_api: "{{ openstack_role_controller }}"
cinder_component_scheduler: "{{ openstack_role_controller }}"
cinder_component_volume: "{{ openstack_role_storage }}"

# MySQL configuration
cinder_mysql_user: cinder
cinder_mysql_password: cinder
cinder_mysql_db: cinder
cinder_mysql_host: "{{ openstack_mysql_host }}"
cinder_mysql_login_password: password

# RabbitMQ configuration
cinder_rabbitmq_user: cinder
cinder_rabbitmq_password: cinder
cinder_rabbitmq_vhost: "{{ openstack_rabbitmq_vhost }}"
cinder_rabbitmq_hosts: "{{ openstack_rabbitmq_hosts }}"

# Keystone configuration
keystone_endpoint_volume_public: "http://{{ openstack_controller_public_host }}:8776/v2/%(tenant_id)s"
keystone_endpoint_volume_internal: "http://{{ openstack_controller_internal_host }}:8776/v2/%(tenant_id)s"
keystone_endpoint_volume_admin: "http://{{ openstack_controller_internal_host }}:8776/v2/%(tenant_id)s"

cinder_keystone_user: cinder
cinder_keystone_password: cinder
cinder_keystone_project: service
cinder_keystone_auth_uri: "http://{{ openstack_controller_public_host }}:5000"
cinder_keystone_identity_uri: "http://{{ openstack_controller_internal_host }}:35357"

# Cinder configuration
cinder_host: "{{ ansible_hostname }}"
cinder_my_ip: "{{ openstack_internal_host }}"

cinder_glance_host: "{{ openstack_controller_internal_host }}"

cinder_api_workers: 2

cinder_az: nova

# Volume configuration
cinder_backends:
  lvm:
    volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
    volume_group: cinder-volumes
    iscsi_protocol: iscsi
    iscsi_helper: tgtadm
