- name: add apt key
  apt_key:
    id: 2C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
  register: result
  until: result|success

- name: add apt repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes

- name: install extra kernel modules
  apt:
    pkg: linux-image-extra-{{ ansible_kernel }}
    state: present

- name: install docker
  apt:
    pkg: docker-engine
    state: present
