- name: ensure admin user
  run_once: true
  keystone_v3_user:
    name: admin
    email: "{{ keystone_admin_email }}"
    password: "{{ keystone_admin_password }}"
    force: "{{ keystone_force_change_password }}"
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"

- name: ensure admin user has admin role on default domain
  run_once: true
  keystone_v3_assignment:
    user: admin
    domain: default
    role: admin
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"

- name: ensure admin user has admin role on admin project
  run_once: true
  keystone_v3_assignment:
    user: admin
    project: admin
    role: admin
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
