- name: ensure keystone identity service
  run_once: true
  keystone_v3_service:
    name: keystone
    type: identity
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"

- name: ensure keystone identity endpoints
  run_once: true
  keystone_v3_endpoint:
    service: keystone
    region: "{{ openstack_region }}"
    interface: "{{ item.key }}"
    url: "{{ item.value }}"
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
  with_dict: "{{ keystone_identity_endpoints }}"
