- name: ensure keystone region
  run_once: true
  keystone_v3_region:
    id: "{{ openstack_region }}"
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
