- include: configure_mysql.yml
  when: keystone_configure_mysql
  tags:
    - keystone

- name: install keystone
  apt:
    pkg: keystone
    state: present
  tags:
    - keystone
    - keystone-install

- name: disable eventlet service
  service:
    name: keystone
    state: stopped
    enabled: no
  tags:
    - keystone
    - keystone-configure

- name: configure keystone
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
  notify:
    - sync keystone db
    - restart apache2
  tags:
    - keystone
    - keystone-configure

- name: copy keystone-admin shim
  copy:
    src: keystone-admin.py
    dest: /var/www/keystone-admin.py
    owner: keystone
    group: keystone
    mode: 0755
  tags:
    - keystone
    - keystone-configure

- name: copy keystone-public shim
  copy:
    src: keystone-public.py
    dest: /var/www/keystone-public.py
    owner: keystone
    group: keystone
    mode: 0755
  tags:
    - keystone
    - keystone-configure

- name: configure apache2
  copy:
    src: wsgi-keystone.conf
    dest: /etc/apache2/sites-enabled/wsgi-keystone.conf
  notify:
    - restart apache2
  tags:
    - keystone
    - keystone-configure

- meta: flush_handlers

- name: ensure sqlite db absent
  file:
    path: /var/lib/keystone/keystone.db
    state: absent
  tags:
    - keystone

- name: wait for keystone api
  wait_for:
    port: 5000
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_region.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_service.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_projects.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_roles.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_users.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_openrc.yml
  tags:
    - keystone
    - keystone-configure
