- name: install keystone
  apt:
    pkg: keystone
    state: present
  tags:
    - keystone
    - keystone-install

- name: disable eventlet service
  service:
    name: keystone
    state: stopped
    enabled: no
  tags:
    - keystone
    - keystone-configure

- include: fernet_keys.yml
  when: keystone_token_provider == "fernet"
  tags:
    - keystone
    - keystone-configure
    - keystone-keys

- include: pki_keys.yml
  when: keystone_token_provider == "pki" or keystone_token_provider == "pkiz"
  tags:
    - keystone
    - keystone-configure
    - keystone-keys

- name: configure keystone
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
  notify:
    - sync keystone db
    - restart apache2
  tags:
    - keystone
    - keystone-configure

- name: copy keystone-admin shim
  copy:
    src: keystone-admin.py
    dest: /var/www/keystone-admin.py
    owner: keystone
    group: keystone
    mode: 0755
  tags:
    - keystone
    - keystone-configure

- name: copy keystone-public shim
  copy:
    src: keystone-public.py
    dest: /var/www/keystone-public.py
    owner: keystone
    group: keystone
    mode: 0755
  tags:
    - keystone
    - keystone-configure

- name: configure apache2
  template:
    src: wsgi-keystone.conf.j2
    dest: /etc/apache2/sites-enabled/wsgi-keystone.conf
  notify:
    - restart apache2
  tags:
    - keystone
    - keystone-configure

- meta: flush_handlers

- name: ensure apache2 started
  service:
    name: apache2
    state: started
  tags:
    - keystone

- name: wait for keystone api
  command: curl -f {{ keystone_identity_endpoints.internal }}
  register: result
  changed_when: false
  until: result|success
  retries: 10
  delay: 2
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_region.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_service.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_projects.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_roles.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_users.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_openrc.yml
  tags:
    - keystone
    - keystone-configure
