- include: configure_mysql.yml
  when: keystone_configure_mysql
  tags:
    - keystone

- name: install keystone
  apt:
    pkg: keystone
    state: present
  tags:
    - keystone
    - keystone-install

- name: configure keystone
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
  notify:
    - sync keystone db
    - restart keystone
  tags:
    - keystone
    - keystone-configure

- meta: flush_handlers

- name: ensure sqlite db absent
  file:
    path: /var/lib/keystone/keystone.db
    state: absent
  tags:
    - keystone

- name: wait for keystone api
  wait_for:
    port: 5000
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_region.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_service.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_projects.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_roles.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_keystone_users.yml
  tags:
    - keystone
    - keystone-configure

- include: configure_openrc.yml
  tags:
    - keystone
    - keystone-configure
