dependencies:
  - role: openstack-common
  - role: ubuntu-cloud-archive

  - role: openstack/lb
    name: heat-api
    listen_port: 8004
    options:
      - httpchk
    tags:
      - heat

  - role: openstack/lb
    name: heat-api-cfn
    listen_port: 8000
    options:
      - httpchk
    tags:
      - heat

  - role: openstack/keystone-service
    service_name: heat
    service_type: orchestration
    service_endpoints: "{{ heat_keystone_orchestration_endpoints }}"
    tags:
      - heat

  - role: openstack/keystone-service
    service_name: heat-cfn
    service_type: cloudformation
    service_endpoints: "{{ heat_keystone_cloudformation_endpoints }}"
    tags:
      - heat

  - role: openstack/keystone-service-user
    user: "{{ heat_keystone_user }}"
    password: "{{ heat_keystone_password }}"
    project: "{{ heat_keystone_project }}"
    tags:
      - heat

  - role: openstack/database
    database: "{{ heat_mysql_db }}"
    user: "{{ heat_mysql_user }}"
    password: "{{ heat_mysql_password }}"
    tags:
      - heat

  - role: openstack/messaging
    vhost: "{{ heat_rabbitmq_vhost }}"
    user: "{{ heat_rabbitmq_user }}"
    password: "{{ heat_rabbitmq_password }}"
    tags:
      - heat
