dependencies:
  - role: openstack-common
  - role: ubuntu-cloud-archive

  - role: openstack/keystone-service
    service_name: heat
    service_type: orchestration
    service_endpoints: "{{ heat_keystone_orchestration_endpoints }}"
    when: heat_configure_keystone
    tags:
      - heat

  - role: openstack/keystone-service
    service_name: heat-cfn
    service_type: cloudformation
    service_endpoints: "{{ heat_keystone_cloudformation_endpoints }}"
    when: heat_configure_keystone
    tags:
      - heat

  - role: openstack/keystone-service-user
    user: "{{ heat_keystone_user }}"
    password: "{{ heat_keystone_password }}"
    project: "{{ heat_keystone_project }}"
    when: heat_configure_keystone
    tags:
      - heat

  - role: openstack/database
    database_name: "{{ heat_mysql_db }}"
    database_user: "{{ heat_mysql_user }}"
    database_password: "{{ heat_mysql_password }}"
    database_login_host: "{{ heat_mysql_host }}"
    database_login_user: root
    database_login_password: "{{ heat_mysql_login_password }}"
    when: heat_configure_mysql
    tags:
      - heat
