- name: install memcached
  apt:
    pkg: memcached
    state: present
  tags:
    - memcached
    - memcached-install

- name: configure memcached
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
  notify:
    - restart memcached
  tags:
    - memcached
    - memcached-configure

- meta: flush_handlers
