heat_configure_keystone: "{{ openstack_role_controller }}"
heat_configure_mysql: "{{ openstack_role_controller }}"
heat_configure_rabbitmq: "{{ openstack_role_controller }}"

# MySQL configuration
heat_mysql_user: heat
heat_mysql_password: heat
heat_mysql_db: heat
heat_mysql_host: "{{ openstack_mysql_host }}"
heat_mysql_login_password: password

# RabbitMQ configuration
heat_rabbitmq_user: heat
heat_rabbitmq_password: heat
heat_rabbitmq_vhost: "{{ openstack_rabbitmq_vhost }}"
heat_rabbitmq_hosts: "{{ openstack_rabbitmq_hosts }}"

# Keystone configuration
heat_keystone_orchestration_endpoints:
  public: "http://{{ openstack_controller_public_host }}:8004/v1/%(tenant_id)s"
  internal: "http://{{ openstack_controller_internal_host }}:8004/v1/%(tenant_id)s"
  admin: "http://{{ openstack_controller_internal_host }}:8004/v1/%(tenant_id)s"

heat_keystone_cloudformation_endpoints:
  public: "http://{{ openstack_controller_public_host }}:8000/v1"
  internal: "http://{{ openstack_controller_internal_host }}:8000/v1"
  admin: "http://{{ openstack_controller_internal_host }}:8000/v1"

heat_keystone_user: heat
heat_keystone_password: heat
heat_keystone_project: service
heat_keystone_auth_uri: "http://{{ openstack_controller_public_host }}:5000/v2.0"
heat_keystone_identity_uri: "http://{{ openstack_controller_internal_host }}:35357"
