dependencies:
  - role: openstack-common
  - role: ubuntu-cloud-archive
  - role: apache2

  - role: openstack/database
    database: "{{ keystone_mysql_db }}"
    user: "{{ keystone_mysql_user }}"
    password: "{{ keystone_mysql_password }}"
    tags:
      - keystone
