# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  (1..3).each do |num|
    config.vm.define "controller#{num}" do |box|
      box.vm.hostname = "controller#{num}"

      box.vm.network "private_network", ip: "10.0.44.10#{num}"
      box.vm.network "private_network", ip: "10.0.55.10#{num}", auto_config: false
    end
  end

  (1..2).each do |num|
    config.vm.define "compute#{num}" do |box|
      box.vm.hostname = "compute#{num}"

      box.vm.network "private_network", ip: "10.0.44.20#{num}"
      box.vm.network "private_network", ip: "10.0.55.20#{num}", auto_config: false

      if num == 2
        box.vm.provision "ansible" do |a|
          a.playbook = "playbook.yml"

          a.groups = {
            "controller" => ["controller1", "controller2", "controller3"],
            "rabbitmq:children" => ["controller"],
            "mysql:children" => ["controller"],
            "compute" => ["compute1", "compute2"],
          }

          a.limit = "all"
        end
      end
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2

    # Workaround for slow DNS resolution on OS X host
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

    # Enable promiscuous mode
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
  end

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = 2048
    v.vmx["numvcpus"] = 2
  end
end
