- name: install horizon
  apt:
    pkg: openstack-dashboard
    state: present
  tags:
    - horizon
    - horizon-install

- name: remove ubuntu theme
  apt:
    pkg: openstack-dashboard-ubuntu-theme
    state: absent
  tags:
    - horizon
    - horizon-install

- name: configure horizon
  template:
    src: local_settings.py.j2
    dest: /etc/openstack-dashboard/local_settings.py
  notify:
    - restart apache2
  tags:
    - horizon
    - horizon-configure

- meta: flush_handlers
