- name: install nova-compute
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: nova_compute_packages[nova_compute_libvirt_virt_type]
  tags:
    - nova-install

# Installed to provide network rootwrap filters for Midonet
- name: install nova-network
  apt:
    pkg: nova-network
    state: present
  when: nova_midonet_integration
  tags:
    - nova-install

- name: ensure nova-network stopped and disabled
  service:
    name: nova-network
    state: stopped
    enabled: no
  when: nova_midonet_integration
  tags:
    - nova-install

- name: configure libvirtd
  template:
    src: libvirtd.conf.j2
    dest: /etc/libvirt/libvirtd.conf
  notify:
    - restart libvirtd
  tags:
    - nova-configure

- name: configure libvirtd qemu
  copy:
    src: midonet-qemu.conf
    dest: /etc/libvirt/qemu.conf
  when: nova_midonet_integration
  notify:
    - restart libvirtd
  tags:
    - nova-configure

- name: configure libvirtd defaults
  copy:
    src: libvirt-bin
    dest: /etc/default/libvirt-bin
  notify:
    - restart libvirtd
  tags:
    - nova-configure

- name: configure nova-compute
  template:
    src: nova-compute.conf.j2
    dest: /etc/nova/nova-compute.conf
  notify:
    - restart nova-compute
  tags:
    - nova-configure

- name: ensure nova user has ssh key pair
  user:
    name: nova
    generate_ssh_key: yes
    ssh_key_type: ecdsa
    ssh_key_bits: 256
  register: nova_user
  tags:
    - nova-configure

- name: configure authorized keys
  template:
    src: ssh/authorized_keys.j2
    dest: /var/lib/nova/.ssh/authorized_keys
    owner: nova
    group: nova
    mode: 0600
  tags:
    - nova-configure
    - nova-distribute-ssh

- name: configure known hosts
  template:
    src: ssh/known_hosts.j2
    dest: /var/lib/nova/.ssh/known_hosts
    owner: nova
    group: nova
    mode: 0600
  tags:
    - nova-configure
    - nova-distribute-ssh

- include: configure_ceph.yml
  when: nova_configure_ceph
  tags:
    - nova-configure

- include: set_libvirt_rbd_secret.yml
  when: nova_configure_ceph
  tags:
    - nova-configure
