- name: install nova-compute
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: nova_compute_packages[nova_compute_libvirt_virt_type]

- name: configure nova-compute
  template:
    src: nova-compute.conf.j2
    dest: /etc/nova/nova-compute.conf
  notify:
    - restart nova-compute
