- name: ensure keystone compute service
  keystone_v3_service:
    name: nova
    type: compute
    state: present
      
    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"

- name: ensure keystone compute endpoints
  keystone_v3_endpoint:
    service: nova
    region: "{{ openstack_region }}"
    interface: "{{ item.key }}"
    url: "{{ item.value }}"
    state: present

    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
  with_dict:
    public: "{{ keystone_endpoint_compute_public }}"
    internal: "{{ keystone_endpoint_compute_internal }}"
    admin: "{{ keystone_endpoint_compute_admin }}"

- name: ensure keystone service user
  keystone_v3_user:
    name: "{{ nova_keystone_user }}"
    password: "{{ nova_keystone_password }}"
    state: present
      
    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"

- name: ensure keystone service user has admin role on service project
  keystone_v3_assignment:
    user: "{{ nova_keystone_user }}"
    project: "{{ nova_keystone_project }}"
    role: admin
   
    endpoint: "{{ keystone_admin_endpoint }}"
    token: "{{ keystone_admin_token }}"
