- name: check if libvirt rbd secret set
  command: virsh secret-get-value {{ nova_rbd_secret_uuid }}
  register: result
  changed_when: false
  failed_when: false

- name: retrieve ceph client key
  command: ceph auth get-key client.cinder
  when: result.rc != 0
  register: key_result
  changed_when: false

- name: generate libvirt rbd secret definition
  template:
    src: secret.xml.j2
    dest: /tmp/secret.xml
  when: result.rc != 0

- name: define libvirt rbd secret
  command: virsh secret-define /tmp/secret.xml
  when: result.rc != 0

- name: set libvirt rbd secret
  command: virsh secret-set-value {{ nova_rbd_secret_uuid }} {{ key_result.stdout }}
  when: result.rc != 0
