dependencies:
  - role: openstack-common
  - role: ubuntu-cloud-archive

  - role: openstack/lb
    name: glance-api
    listen_port: 9292
    options:
      - httpchk
    tags:
      - glance

  - role: openstack/lb
    name: glance-registry
    listen_port: 9191
    tags:
      - glance

  - role: openstack/keystone-service
    service_name: glance
    service_type: image
    service_endpoints: "{{ glance_keystone_image_endpoints }}"
    tags:
      - glance

  - role: openstack/keystone-service-user
    user: "{{ glance_keystone_user }}"
    password: "{{ glance_keystone_password }}"
    project: "{{ glance_keystone_project }}"
    tags:
      - glance

  - role: openstack/database
    database: "{{ glance_mysql_db }}"
    user: "{{ glance_mysql_user }}"
    password: "{{ glance_mysql_password }}"
    tags:
      - glance
